=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/test/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="group">
    <xsd:complexType>
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
        <xsd:element name="stagiaire">
        <xsd:complexType>
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element name="prenom" type="xsd:string"/>
            <xsd:element name="age" type="xsd:string"/>
        </xsd:sequence>
        </xsd:complexType>
        </xsd:element>
    </xsd:sequence>
    </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/test/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE group SYSTEM "test.dtd"> -->
<?xml-stylesheet type="text/xsl" href="test.xsl"?>
<group>
<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="test.xsd"> -->
    <stagiaire>
        <nom>N1</nom>
        <prenom>P1</prenom>
        <age>18</age>
    </stagiaire>
    <stagiaire>
        <nom>N2</nom>
        <prenom>P2</prenom>
        <age>19</age>
    </stagiaire>
    <stagiaire>
        <nom>N3</nom>
        <prenom>P3</prenom>
        <age>20</age>
    </stagiaire>
</group>
