=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2015/dtd_file1.dtd
<!ELEMENT seances (seance+)>
<!ATTLIST seance jour CDATA #REQUIRED
                 debuE CDATA #REQUIRED
                 fin CDATA #REQUIRED
>
<!ELEMENT seance (salle,module,formateur,groupe)>
<!ELEMENT salle (#PCDATA)>
<!ELEMENT module (#PCDATA)>
<!ELEMENT formateur (#PCDATA)>
<!ELEMENT groupe (#PCDATA)>

=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2015/xml_file1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE seances SYSTEM "dtd_file1.dtd"> -->
<?xml-stylesheet type="text/xsl" href="xsl_file1.xsl"?>
<seances>
	<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xsd_file1.xsd"> -->
	<seance jour="Iundi" debuE="09:00:00" fin="10:30:00">
		<salle>S1</salle>
		<module>SGBDR I</module>
		<formateur>CHAKIR Said</formateur>
		<groupe>TDI201</groupe>
	</seance>
	<seance jour="Iundi" debuE="10:30:00" fin="13:00:00">
		<salle>S2</salle>
		<module>Reseaux</module>
		<formateur>TAHIR Nadia</formateur>
		<groupe>TDI201</groupe>
	</seance>
	<seance jour="mardi" debuE="08:00:00" fin="10:30:00">
		<salle>S1</salle>
		<module>SGBDR I</module>
		<formateur>CHAKIR Said</formateur>
		<groupe>TDI202</groupe>
	</seance>
</seances>
