=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2020/dtd_file6.dtd
<!ELEMENT FestivaleRire (participant+)>
<!ATTLIST participant idp CDATA #REQUIRED>
<!ELEMENT participant (nom,prenom,civilite,tel,ville,blague)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT civilite (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT ville (idv,libellev)>
<!ELEMENT idv (#PCDATA)>
<!ELEMENT libellev (#PCDATA)>
<!ELEMENT blague (titre,contenu,nbrvote)>
<!ATTLIST blague idb CDATA #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT contenu (#PCDATA)>
<!ELEMENT nbrvote (#PCDATA)>

=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2020/xml_file6.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE FestivaleRire SYSTEM "dtd_file6.dtd">
<?xml-stylesheet href="xsl_file6.xsl" type="text/xsl"?>
<FestivaleRire>
<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xsd_file6.xsd"> -->
    <participant idp="1">
        <nom>nom1</nom>
        <prenom>prenom1</prenom>
        <civilite>Mr</civilite>
        <tel>0000000000</tel>
        <ville>
            <idv>1</idv>
            <libellev>Rabat</libellev>
        </ville>
        <blague idb="1">
            <titre>titre1</titre>
            <contenu>contenu1</contenu>
            <nbrvote>2</nbrvote>
        </blague>
    </participant>
    <participant idp="2">
        <nom>nom2</nom>
        <prenom>prenom2</prenom>
        <civilite>Mr</civilite>
        <tel>0000000000</tel>
        <ville>
            <idv>1</idv>
            <libellev>Fes</libellev>
        </ville>
        <blague idb="2">
            <titre>titre2</titre>
            <contenu>contenu2</contenu>
            <nbrvote>3</nbrvote>
        </blague>
    </participant>
</FestivaleRire>
