=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2019/dtd_file5.dtd
<!ELEMENT pelerinages (pelerinage)>
<!ATTLIST pelerinage annee CDATA #REQUIRED >
<!ELEMENT pelerinage (pelerin+)>
<!ATTLIST pelerin num CDATA #REQUIRED
                  sexe CDATA #REQUIRED
                  nationalite CDATA #REQUIRED
                  age CDATA #REQUIRED
                  idaccompagnateur CDATA
>
<!ELEMENT pelerin(nom,prenom,dossier_medical)>
<!ELEMENT nom #PCDATA>
<!ELEMENT prenom #PCDATA>
<!ELEMENT dossier_medical(maladie|enceinte|EMPTY)*>
<!ATTLIST dossier_medical (group_sanguin CDATA #REQUIRED)>
<!ELEMENT maladie (#PCDATA)>
<!ELEMENT enceinte EMPTY>
<!ATTLIST enceinte(semaine CDATA #REQUIRED) >

=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2019/xml_file5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE pelerinages SYSTEM "dtd_file5.dtd"> -->

<?xml-stylesheet type="text/xsl" href="xsl_file5.xsl"?>
<pelerinages
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xsd_file5.xsd">
    <pelerinage annee="2018">
        <pelerin num="p1" sexe="M" nationalite="marocain" age="50">
            <nom>Alaoui</nom>
            <prenom>Amine</prenom>
            <dossier_medical group_sanguin="O+">
                <maladie>hypertension</maladie>
            </dossier_medical>
        </pelerin>
        <pelerin num="p2" sexe="F" nationalite="libanaise" age="40" idaccompagnateur="P1234">
            <nom>Talal</nom>
            <prenom>Sara</prenom>
            <dossier_medical group_sanguin="A+">
                <enceinte semaine="4"/>
            </dossier_medical>
        </pelerin>
        <pelerin num="p3" sexe="H" nationalite="egyptien" age="45">
            <nom>Mabdouli</nom>
            <prenom>Yassir</prenom>
            <dossier_medical group_sanguin="B+">         
            </dossier_medical>
        </pelerin>
    </pelerinage>
</pelerinages>
