=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2018/dtd_file4.dtd
<!ELEMENT Catalogue (Plante+)>
<!ELEMENT Plante (NomCommun,NomBotanique,zone,Eclairage,Prix,QuantiteStock)>
<!ELEMENT NomCommun (#PCDATA)>
<!ELEMENT NomBotanique (#PCDATA)>
<!ELEMENT zone (#PCDATA)>
<!ELEMENT Eclairage (#PCDATA)>
<!ELEMENT Prix (#PCDATA)>
<!ELEMENT QuantiteStock (#PCDATA)>

=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2018/xml_file4.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Catalogue SYSTEM "dtd_file4.dtd">
<?xml-stylesheet type="text/xsl" href="xsl_file4.xsl"?>
<Catalogue>
<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xsd_file4.xsd"> -->
    <Plante>
        <NomCommun>bloodroot</NomCommun>
        <NomBotanique>sanguinaria canadensis</NomBotanique>
        <zone>4</zone>
        <Eclairage>ombrage</Eclairage>
        <Prix>25</Prix>
        <QuantiteStock>0</QuantiteStock>
    </Plante>
    <Plante>
        <NomCommun>columbine</NomCommun>
        <NomBotanique>aquilegia canadensis</NomBotanique>
        <zone>3</zone>
        <Eclairage>ombrage</Eclairage>
        <Prix>100</Prix>
        <QuantiteStock>7</QuantiteStock>
    </Plante>
    <Plante>
        <NomCommun>marsh marigold</NomCommun>
        <NomBotanique>caltha plustris</NomBotanique>
        <zone>4</zone>
        <Eclairage>Ensoleille</Eclairage>
        <Prix>70</Prix>
        <QuantiteStock>51</QuantiteStock>
    </Plante>
    <Plante>
        <NomCommun>cowslip</NomCommun>
        <NomBotanique>caltha plustris</NomBotanique>
        <zone>4</zone>
        <Eclairage>ombrage</Eclairage>
        <Prix>100</Prix>
        <QuantiteStock>30</QuantiteStock>
    </Plante>
    <Plante>
        <NomCommun>dutchman's-breeches</NomCommun>
        <NomBotanique>diecentra cucullaria</NomBotanique>
        <zone>3</zone>
        <Eclairage>Ensoleille</Eclairage>
        <Prix>80</Prix>
        <QuantiteStock>120</QuantiteStock>
    </Plante>
    <Plante>
        <NomCommun>giger, wild</NomCommun>
        <NomBotanique>asarum canadense</NomBotanique>
        <zone>3</zone>
        <Eclairage>Ensoleille</Eclairage>
        <Prix>90</Prix>
        <QuantiteStock>92</QuantiteStock>
    </Plante>
</Catalogue>
