=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2014/dtd_file0.dtd
<!ELEMENT FOOT (JOURNEE+)>
<!ATTLIST FOOT DIVISION CDATA #REQUIRED>
<!ELEMENT JOURNEE (MATCH+)>
<!ATTLIST JOURNEE NUMERO CDATA #REQUIRED
                  DATE CDATA #REQUIRED
>
<!ELEMENT MATCH EMPTY>
<!ATTLIST MATCH LOCAUX CDATA #REQUIRED
                VISITEURS CDATA #REQUIRED
                BUTS_LOCAUX CDATA #REQUIRED
                BUTS_VISITEURS CDATA #REQUIRED
>

=== karimch-50/Ofppt-Correction-EFF-2010-2020/Correction_eff_XML_Th_EFF/EFF_2014/xml_file0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FOOT SYSTEM "dtd_file0.dtd">
<?xml-stylesheet href="xsl_file0.xsl" type="text/xsl"?>
<FOOT DIVISION="1">
<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xsd_file0.xsd"> -->
    <JOURNEE NUMERO="1" DATE="01/09/2013">
        <MATCH LOCAUX="WAC" VISITEURS="RCA" BUTS_LOCAUX="1" BUTS_VISITEURS="2"/>
        <MATCH LOCAUX="DHJ" VISITEURS="OCK" BUTS_LOCAUX="2" BUTS_VISITEURS="1"/>
        <MATCH LOCAUX="HUSA" VISITEURS="MAC" BUTS_LOCAUX="0" BUTS_VISITEURS="0"/>
        <MATCH LOCAUX="FAR" VISITEURS="WAF" BUTS_LOCAUX="1" BUTS_VISITEURS="1"/>
    </JOURNEE>
    <JOURNEE NUMERO="2" DATE="08/09/2013">
        <MATCH LOCAUX="RCA" VISITEURS="FAR" BUTS_LOCAUX="3" BUTS_VISITEURS="2"/>
        <MATCH LOCAUX="WAF" VISITEURS="HUSA" BUTS_LOCAUX="0" BUTS_VISITEURS="1"/>
        <MATCH LOCAUX="MAS" VISITEURS="DHJ" BUTS_LOCAUX="0" BUTS_VISITEURS="1"/>
        <MATCH LOCAUX="KAC" VISITEURS="WAC" BUTS_LOCAUX="1" BUTS_VISITEURS="1"/>
    </JOURNEE>
    <JOURNEE NUMERO="3" DATE="15/09/2013">
        <MATCH LOCAUX="ASS" VISITEURS="MAT" BUTS_LOCAUX="1" BUTS_VISITEURS="3"/>
        <MATCH LOCAUX="WAC" VISITEURS="WAF" BUTS_LOCAUX="3" BUTS_VISITEURS="2"/>
        <MATCH LOCAUX="DHJ" VISITEURS="FUS" BUTS_LOCAUX="1" BUTS_VISITEURS="0"/>
        <MATCH LOCAUX="MAS" VISITEURS="RCA" BUTS_LOCAUX="1" BUTS_VISITEURS="2"/>
    </JOURNEE>
    <JOURNEE NUMERO="4" DATE="22/09/2013">
        <MATCH LOCAUX="FUS" VISITEURS="MAS" BUTS_LOCAUX="1" BUTS_VISITEURS="0"/>
        <MATCH LOCAUX="MAT" VISITEURS="WAC" BUTS_LOCAUX="2" BUTS_VISITEURS="0"/>
        <MATCH LOCAUX="KAC" VISITEURS="DHJ" BUTS_LOCAUX="1" BUTS_VISITEURS="1"/>
        <MATCH LOCAUX="ASS" VISITEURS="FAR" BUTS_LOCAUX="0" BUTS_VISITEURS="0"/>
    </JOURNEE>
</FOOT>
